version: '3'

networks:
  redis-network:
    driver: bridge

volumes:
  redis-volume:

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      redis-network:
    volumes: 
      - "redis-volume:/data/db"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    networks:
      redis-network:
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
