apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec:
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
      - name: conversao-peso
        image: genilsoncruz/conversao-peso:v1
        ports:
        - containerPort: 80
          name: http