apiVersion: v1
kind: Service
metadata:
  name: pedelogo-catalogo-service
spec:
  selector:
    app: pedelogo-catalogo
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer
