apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedelogo-catalogo-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pedelogo-catalogo
  template:
    metadata:
      labels:
        app: pedelogo-catalogo
    spec:
      initContainers:
        - name: init
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mongo-service.default.svc.cluster.local; do echo Aguardando o BD; sleep 2; done"]
      containers:
      - name: pedelogo-catalogo
        image:  genilsoncruz/pedelogo-catalogo:v1
        resources:
          requests:
            memory: 32Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 5          
        startupProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        env:
        - name: Mongo__Host
          value: "mongo-service"
        - name: Mongo__User
          value: "mongouser"
        - name: Mongo__Password
          value: "mongopwd"
        - name: Mongo__Port
          value: "27017"
        - name: Mongo__DataBase
          value: "admin"