apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb      
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongodb-data
        #resources:
        #  requests:
        #    memory: 256Mi
        #    cpu: 300m
        #  limits:
        #    memory: 256Mi
        #    cpu: 300m
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - mongo --port 27017 --eval "rs.status()" | grep -vq "REMOVED"
          initialDelaySeconds: 45
          timeoutSeconds: 5        
        env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: "mongouser"
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: "mongopwd"
      volumes:
        - name: mongodb-data
          hostPath:
            path: /volumes/mongodb