version: '3'

networks:
  rotten-potatoes-network:
    driver: bridge

volumes:
  rotten-potatoes-volume:

services:
  app:
    image: rotten-potatoes:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
    networks:
      - "rotten-potatoes-network"
    ports:
      - "5000:5000"
    depends_on:
    - "mongodb"

  mongodb:
    image: mongo:5.0.0
    networks:
    - "rotten-potatoes-network"
    volumes:
    - "rotten-potatoes-volume:/data/db"
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd      