apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      initContainers:
        - name: init
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mongo-service.default.svc.cluster.local; do echo Aguardando o BD; sleep 2; done"]
      containers:
      - name: rotten-potatoes
        image:  genilsoncruz/rotten-potatoes:v1
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: MONGODB_HOST
          value: "mongo-service"
        - name: MONGODB_USERNAME
          value: "mongouser"
        - name: MONGODB_PASSWORD
          value: "mongopwd"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DB
          value: "admin"