apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres      
        image: postgres:14.5
        ports:
        - containerPort: 5432
        #volumeMounts:
        #  - mountPath: /data/db
        #    name: postgres-data
        env:
        - name: POSTGRES_USER
          value: kubedevnews
        - name: POSTGRES_PASSWORD
          value: Pg#123        
      #volumes:
      #  - name: postgres-data
      #    hostPath:
      #      path: /volumes/postgres