apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: genilsoncruz/conversao-temperatura:v1
        ports:
        - containerPort: 8080
          name: http