apiVersion: v1
kind: Service
metadata:
  name: service-conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP